## Open CV Taller 1

## Bibliotecas

In [6]:
import skimage as ski
import cv2
import numpy  as np

In [7]:
camera = ski.data.camera()

In [8]:

img = cv2.imread("C:\\Users\\User\\Pictures\\cedula_daniel.png",1)


if img is None:
    print("Image not loaded correctly!")    
else:
    print("OpenCV is installed and working correctly!")
    print(img[20,20])
    blue, green, red = cv2.split(img)
    #print(img.shape)
    #print(img.dtype)
    cv2.imshow("cuadro",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

OpenCV is installed and working correctly!
[143 143 148]


In [ ]:
blank = np.zeros(img.shape[:2], dtype='uint8')

center_coordinates = (144, 233)

radius = 10

mask = cv2.circle(blank, center_coordinates, radius, 255, -1)

masked = cv2.bitwise_and(img, img, mask=mask)
cv2.imshow('Output', masked)

: 

In [4]:
matriz=[[0,0,0,0],[0,0,0,0]]
img = numpy.array(matriz)
print(img)

img=numpy.zeros((300,300),numpy.uint8)
cv2.imshow("Imagen Negra",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0 0]
 [0 0 0 0]]


In [5]:
img=numpy.ones((200,200,3),numpy.uint8)*255
img[:]=(143 ,143,148)
print(img[50,50])
for x in range(200):
    for y in range(200):
        if x%50==0 or y%50==0:
            img[x,y]=(145,0,143)
            
cv2.imwrite("rejilla.png",img)
cv2.imshow("White Image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[143 143 148]
